---
# NVIDIA Driver Settings
driver_version: "470.161.03"
driver_script_name: "NVIDIA-Linux-x86_64-{{ driver_version }}.run"
driver_url: "https://us.download.nvidia.com/XFree86/Linux-x86_64/{{ driver_version }}/{{ driver_script_name }}"
