---
- name: Add Nvidia Docker apt key.
  become: yes
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    id: C95B321B61E88C1809C4F759DDCAE044F796ECB0
    state: present

- name: Add Nvidia Docker apt repository.
  become: yes
  apt_repository:
    repo: "{{ item }}"
    filename: nvidia-docker
    state: present
    update_cache: yes
  with_items:
    - deb https://nvidia.github.io/libnvidia-container/ubuntu18.04/amd64 /
    - deb https://nvidia.github.io/nvidia-container-runtime/ubuntu18.04/amd64 /
    - deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64 /

- name: Install Nvidia Container Toolkit..
  become: yes
  apt:
    name: nvidia-container-toolkit
    state: present
